server:
  port: 8010

spring:
  sql:
    init:
      platform: mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc://mysql:localhost:3306/fusers
    username: root
    password: coderslab
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
